config/routes.rb
Rails.application.routes.draw do
  resources :words do
    collection do
      get :test
      get :question
      post :answer
      get :answer_sheet
    end
  end

  devise_for :users

  root 'words#test'

end

app/models/temp_word.rb
class TempWord < ActiveRecord::Base
  self.per_page = 1
  belongs_to :word

  def self.question_set(user_id, page_no = nil)
    page_no = 1 if page_no.nil?
    question = where(user_id: user_id).order(:id).paginate(page: page_no).first

    answer_options = all.sample(3)
    answer_options.to_a.push question
    answers = answer_options.shuffle

    question_set = Hash.new
    question_set[question.word_str] = answers
    question_set
  end

  def mark_answer(answer)
    if self.word_str == answer
      self.correct_answer_increment
      return true
    else
      self.wrong_answer_increment
      return false
    end
  end

  def correct_answer_increment
    self.update_attribute(:num_correct, self.num_correct.to_i + 1)
    self.update_attribute(:num_correct_seq, self.num_wrong.to_i + 1)
  end

  def wrong_answer_increment
    self.update_attribute(:num_wrong, self.num_wrong.to_i + 1)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_responses
end

app/models/user_response.rb
class UserResponse < ActiveRecord::Base
  belongs_to :word
  belongs_to :user
end

app/models/word.rb
class Word < ActiveRecord::Base
  self.per_page = 1

  validates_presence_of :word_str
  validates_uniqueness_of :word_str
  has_many :user_responses
  
  def self.question_set(page_no = nil)
    page_no = 1 if page_no.nil?
    question = all.order(:id).paginate(page: page_no).first

    answer_options = all.sample(3)
    answer_options.to_a.push question
    answers = answer_options.shuffle

    question_set = Hash.new
    question_set[question.word_str] = answers
    question_set
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  def test
    if params[:page].nil?
      if TempWord.where(user_id: current_user.id).count == 0
        populate_temp_table
        UserResponse.where(user_id: current_user.id).delete_all
        @page =  1
      else
        @page = params[:page].nil? ? UserResponse.where(user_id: current_user.id).count : params[:page].to_i
      end
    else
      @page = params[:page].to_i
    end


    @question = TempWord.question_set(current_user.id, @page)

    seq_count = current_user.user_responses.count
    correct_count = current_user.user_responses.where(answered_correctly: true).count

    @seq_per = (( seq_count.to_f / 10.to_f ) * 100 ).to_i
    @correct_per = current_user.user_responses.count != 0 ? (( correct_count.to_f / seq_count.to_f ) * 100 ).to_i : 0
    @correct_answer = current_user.user_responses.last.answered_correctly if current_user.user_responses.last

  end

  def answer
    question_id = params[:question]
    answer   = params[:answer]
    page     = params[:page].to_i

    word = TempWord.find_by_word_str question_id
    correct_answer = word.mark_answer(answer)

    user_resp = UserResponse.find_or_create_by(
      user_id: current_user.id,
      word_id: word.id
    )
    user_resp.update_attribute(:answered_correctly, correct_answer)

    #@mastered = word.user_responses.where(answered_correctly: true, user_id: current_user.id).count > 2
    if current_user.user_responses.count < 10
      @redirect_path  = test_words_path(page: (page + 1))
    else
      @redirect_path = answer_sheet_words_path
    end

    seq_count = current_user.user_responses.count
    correct_count = current_user.user_responses.where(answered_correctly: true).count

    @seq_per = (( seq_count.to_f / 10.to_f ) * 100 ).to_i
    @correct_per = current_user.user_responses.count != 0 ? (( correct_count.to_f / seq_count.to_f ) * 100 ).to_i : 0
    @correct_answer = current_user.user_responses.last.answered_correctly if current_user.user_responses.last

    render json: { redirect_path: @redirect_path, seq_per: @seq_per, correct_per: @correct_per, correct_answer: @correct_answer }
  end

  def answer_sheet
     @answers = current_user.user_responses
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_word
    @word = Word.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def word_params
    params.require(:word).permit(:word_str, :num_tested, :num_correct, :num_correct_seq, :num_wrong, :first_tested, :last_tested)
  end

  def populate_temp_table
    TempWord.where(user_id: current_user.id).delete_all
    words = Word.all.sample(10)
    words.each do |word|
      TempWord.create(
        user_id: current_user.id,
        word_str: word.word_str,
        word_id: word.id
      )
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize(boolean)
    boolean ? 'Yes' : 'No'
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<span class=pull-right>
  <% if current_user %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</span>
<%= yield %>

</body>
</html>

app/views/words/_form.html.haml
= form_for @word do |f|
  - if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :word_str
    = f.text_field :word_str
  .field
    = f.label :num_tested
    = f.number_field :num_tested
  .field
    = f.label :num_correct
    = f.number_field :num_correct
  .field
    = f.label :num_correct_seq
    = f.number_field :num_correct_seq
  .field
    = f.label :num_wrong
    = f.number_field :num_wrong
  .field
    = f.label :first_tested
    = f.datetime_select :first_tested
  .field
    = f.label :last_tested
    = f.datetime_select :last_tested
  .actions
    = f.submit 'Save'

app/views/words/answer_sheet.html.haml
.col-md-8.col-md-offset-2
  %h1 Your responses

  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %td
          %b Word
        %td
          %b Result
    %tbody
      - @answers.each do |answer|
        %tr
          %td= answer.word.word_str
          %td= humanize answer.answered_correctly

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', @word
\|
= link_to 'Back', words_path

app/views/words/index.html.haml
%h1 Listing words

%table.table
  %tr
    %th Word str
    %th Num tested
    %th Num correct
    %th Num correct seq
    %th Num wrong
    %th First tested
    %th Last tested
    %th
    %th
    %th

  - @words.each do |word|
    %tr
      %td= word.word_str
      %td= word.num_tested
      %td= word.num_correct
      %td= word.num_correct_seq
      %td= word.num_wrong
      %td= word.first_tested
      %td= word.last_tested
      %td= link_to 'Show', word
      %td= link_to 'Edit', edit_word_path(word)
      %td= link_to 'Destroy', word, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Word', new_word_path

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', words_path

app/views/words/show.html.haml
%p#notice= notice

%p
  %b Word str:
  = @word.word_str
%p
  %b Num tested:
  = @word.num_tested
%p
  %b Num correct:
  = @word.num_correct
%p
  %b Num correct seq:
  = @word.num_correct_seq
%p
  %b Num wrong:
  = @word.num_wrong
%p
  %b First tested:
  = @word.first_tested
%p
  %b Last tested:
  = @word.last_tested

= link_to 'Edit', edit_word_path(@word)
\|
= link_to 'Back', words_path

app/views/words/test.html.erb
<script type="text/javascript">
  var correct_per = <%= @correct_per %>
  var seq_per     = <%= @seq_per %>
  var page        = <%= @page %>
  var redirect_path = '<%= "/words/test/" + ( @page + 1).to_s %>'

</script>
<div class=container >
  <div class=row>
    <div class=" col-md-8 col-md-offset-1" >
      <h1 id=reportalert>
      </h1>
      <div id=results>
          <div class=question-block>
            <h1 id=question><%= @question.keys.first %></h1>
            <%= form_tag answer_words_path, remote: true, update: { success: "cart", failure: "error" }, id: 'question_form' do %>
              <%= hidden_field_tag :question, @question.keys.first %>
              <%= hidden_field_tag :page, @page %>
              <div>
                <%= submit_tag "Option 1", name: :answer, value: @question[@question.keys.first][0].word_str, class: 'btn btn-mini btn-success' %>

              </div>
              <div>
                <%= submit_tag "Option 2", name: :answer, value: @question[@question.keys.first][1].word_str, class: 'btn btn-mini btn-success' %>

              </div>
              <div>
                <%= submit_tag "Option 3", name: :answer, value: @question[@question.keys.first][2].word_str, class: 'btn btn-mini btn-success' %>

              </div>
              <div>
                <%= submit_tag "Option 4", name: :answer, value: @question[@question.keys.first][3].word_str, class: 'btn btn-mini btn-success' %>

              </div>
            <% end %>
            <div id=status_bar></div>
          </div>
      </div>
    </div>
    <div class=col-md-3>
      <div class=chart data-percent = 0>
        <div class=percent></div>
      </div>
    <div>
    <div class=col-md-2>
      <br/>
      <br/>
      <br/>
      <br/>
      <%= link_to "Previous", "/words/test?page=#{@page - 1}", class: 'btn btn-primary' %>
    </div>
  </div>
</div>